package main

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var shellInitCmd = &cobra.Command{
	Use:   "shell-init [zsh|bash|powershell]",
	Short: "Output shell integration code to eval in your shell config",
	Long: `Outputs shell integration code for the given shell.

Add to the end of your ~/.zshrc or ~/.bashrc (after PATH is set):

  export PATH="$HOME/.local/bin:$PATH"
  eval "$(omgitworks shell-init zsh)"   # or: bash

For PowerShell, add to your $PROFILE:

  $env:Path = "$HOME\.local\bin;$env:Path"
  Invoke-Expression (& omgitworks shell-init powershell | Out-String)

This sets up the 'gws' shell function with tab completion. Because the
function is generated by the binary at shell startup, it always reflects
the current version of omgitworks — no manual updates needed.`,
	Args:      cobra.ExactArgs(1),
	ValidArgs: []string{"zsh", "bash", "powershell"},
	RunE:      runShellInit,
}

func init() {
	rootCmd.AddCommand(shellInitCmd)
}

const zshInitTemplate = `# omgitworks shell integration — do not edit, managed via shell-init
if ! type compdef &>/dev/null; then
  autoload -U compinit && compinit
fi
function omgw() {
  local _dest _arg
  if [[ $# -eq 0 ]]; then
    {BIN}
    return
  fi
  case "$1" in
    list|init|add|refresh|print-workspace|tag|user|completion|shell-init|help|__*) {BIN} "$@" ;;
    worktree)
      case "$2" in
        list|align|add|remove|rm|""|-*) {BIN} "$@" ;;
        *)
          # Help output goes to stdout; never capture it as a destination.
          for _arg in "${@:3}"; do
            case "$_arg" in
              -h|--help) {BIN} "$@"; return ;;
            esac
          done
          _dest="$({BIN} "$@" -q 2>/dev/tty </dev/tty)"
          [[ -n "$_dest" ]] && cd "$_dest"
          ;;
      esac
      ;;
    cd)
      if [[ -n "$2" ]]; then
        {BIN} "$@"
        return
      fi
      _dest="$({BIN} cd -q 2>/dev/tty </dev/tty)"
      [[ -n "$_dest" ]] && cd "$_dest"
      ;;
    -p|--parent|parent)
      _dest="$({BIN} parent "$2" -q 2>/dev/tty </dev/tty)"
      [[ -n "$_dest" ]] && cd "$_dest"
      ;;
    -*)
      {BIN} "$@"
      ;;
    *)
      if [[ "$2" == "-p" || "$2" == "--parent" ]]; then
        _dest="$({BIN} parent "$1" -q 2>/dev/tty </dev/tty)"
      elif [[ "$2" == "-wt" ]]; then
        if [[ -n "$3" ]]; then
          _dest="$({BIN} "$1" --worktree "$3" -q 2>/dev/tty </dev/tty)"
        else
          _dest="$({BIN} "$1" --worktree -q 2>/dev/tty </dev/tty)"
        fi
        [[ -n "$_dest" ]] && cd "$_dest"
        return
      else
        _dest="$({BIN} "$1" -q 2>/dev/tty </dev/tty)"
      fi
      [[ -n "$_dest" ]] && cd "$_dest"
      ;;
  esac
}
# Compatibility: gws was the command before the rename to omgw.
function gws() { omgw "$@"; }
source <({BIN} completion zsh)
compdef _omgitworks omgw
compdef _omgitworks gws
`

const bashInitTemplate = `# omgitworks shell integration — do not edit, managed via shell-init

# Ensure bash-completion helpers are available for tab completion.
# Cobra's generated completion script requires _get_comp_words_by_ref
# which comes from the bash-completion package.
if ! type _get_comp_words_by_ref &>/dev/null; then
  if [[ -r /usr/local/etc/profile.d/bash_completion.sh ]]; then
    source /usr/local/etc/profile.d/bash_completion.sh
  elif [[ -r /opt/homebrew/etc/profile.d/bash_completion.sh ]]; then
    source /opt/homebrew/etc/profile.d/bash_completion.sh
  elif [[ -r /usr/share/bash-completion/bash_completion ]]; then
    source /usr/share/bash-completion/bash_completion
  elif [[ -r /etc/bash_completion ]]; then
    source /etc/bash_completion
  fi
fi

function omgw() {
  local dest arg
  if [[ $# -eq 0 ]]; then
    {BIN}
    return
  fi
  case "$1" in
    list|init|add|refresh|print-workspace|tag|user|completion|shell-init|help|__*) {BIN} "$@"; return ;;
    worktree)
      case "$2" in
        list|align|add|remove|rm|""|-*) {BIN} "$@" ;;
        *)
          # Help output goes to stdout; never capture it as a destination.
          for arg in "${@:3}"; do
            case "$arg" in
              -h|--help) {BIN} "$@"; return ;;
            esac
          done
          dest="$({BIN} "$@" -q 2>/dev/tty </dev/tty)"
          [[ -n "$dest" ]] && cd "$dest"
          ;;
      esac
      ;;
    cd)
      if [[ -n "$2" ]]; then
        {BIN} "$@"
        return
      fi
      dest="$({BIN} cd -q 2>/dev/tty </dev/tty)"
      [[ -n "$dest" ]] && cd "$dest"
      ;;
    -p|--parent|parent)
      dest="$({BIN} parent "$2" -q 2>/dev/tty </dev/tty)"
      [[ -n "$dest" ]] && cd "$dest"
      ;;
    -*)
      {BIN} "$@"
      ;;
    *)
      if [[ "$2" == "-p" || "$2" == "--parent" ]]; then
        dest="$({BIN} parent "$1" -q 2>/dev/tty </dev/tty)"
      elif [[ "$2" == "-wt" ]]; then
        if [[ -n "$3" ]]; then
          dest="$({BIN} "$1" --worktree "$3" -q 2>/dev/tty </dev/tty)"
        else
          dest="$({BIN} "$1" --worktree -q 2>/dev/tty </dev/tty)"
        fi
        [[ -n "$dest" ]] && cd "$dest"
        return
      else
        dest="$({BIN} "$1" -q 2>/dev/tty </dev/tty)"
      fi
      [[ -n "$dest" ]] && cd "$dest"
      ;;
  esac
}
# Compatibility: gws was the command before the rename to omgw.
function gws() { omgw "$@"; }
source <({BIN} completion bash)
complete -o default -F __start_omgitworks omgw
complete -o default -F __start_omgitworks gws
`

const powershellInitTemplate = `# omgitworks shell integration — do not edit, managed via shell-init
function omgw {
    if ($args.Count -eq 0) {
        & {BIN}
        return
    }

    $first = $args[0]
    $rest = @()
    if ($args.Count -gt 1) {
        $rest = $args[1..($args.Count - 1)]
    }

    switch -Regex ($first) {
        '^(list|init|add|refresh|print-workspace|tag|user|completion|shell-init|help|__.*)$' {
            & {BIN} @args
            return
        }
        '^worktree$' {
            if ($rest.Count -eq 0) {
                & {BIN} @args
                return
            }
            $second = $rest[0]
            switch ($second) {
                { $_ -in 'list', 'align', 'add', 'remove', 'rm' -or $_ -like '-*' } {
                    & {BIN} @args
                    return
                }
                # Help output goes to stdout; never capture it as a destination.
                { $rest -contains '-h' -or $rest -contains '--help' } {
                    & {BIN} @args
                    return
                }
                default {
                    $dest = & {BIN} @args -q 2>&1 | Where-Object { $_ -is [string] }
                    if ($dest) { Set-Location $dest }
                    return
                }
            }
        }
        '^cd$' {
            if ($rest.Count -gt 0) {
                & {BIN} @args
                return
            }
            $dest = & {BIN} cd -q 2>&1 | Where-Object { $_ -is [string] }
            if ($dest) { Set-Location $dest }
            return
        }
        '^(-p|--parent|parent)$' {
            $second = if ($rest.Count -gt 0) { $rest[0] } else { $null }
            $dest = & {BIN} parent $second -q 2>&1 | Where-Object { $_ -is [string] }
            if ($dest) { Set-Location $dest }
            return
        }
        '^-' {
            & {BIN} @args
            return
        }
        default {
            $second = if ($rest.Count -gt 0) { $rest[0] } else { $null }

            if ($second -eq '-p' -or $second -eq '--parent') {
                $dest = & {BIN} parent $first -q 2>&1 | Where-Object { $_ -is [string] }
                if ($dest) { Set-Location $dest }
                return
            }
            elseif ($second -eq '-wt') {
                if ($rest.Count -gt 1) {
                    $branch = $rest[1]
                    $dest = & {BIN} $first --worktree $branch -q 2>&1 | Where-Object { $_ -is [string] }
                } else {
                    $dest = & {BIN} $first --worktree -q 2>&1 | Where-Object { $_ -is [string] }
                }
                if ($dest) { Set-Location $dest }
                return
            }
            else {
                $dest = & {BIN} $first -q 2>&1 | Where-Object { $_ -is [string] }
                if ($dest) { Set-Location $dest }
                return
            }
        }
    }
}
# Compatibility: gws was the command before the rename to omgw.
function gws { omgw @args }
& {BIN} completion powershell | Invoke-Expression
(& {BIN} completion powershell) -replace 'omgitworks', 'omgw' | Invoke-Expression
(& {BIN} completion powershell) -replace 'omgitworks', 'gws' | Invoke-Expression
`

func runShellInit(_ *cobra.Command, args []string) error {
	script, err := renderShellInit(args[0], "omgitworks")
	if err != nil {
		return err
	}
	fmt.Print(script)
	return nil
}

// renderShellInit returns the shell integration for shell, invoking bin as the binary.
func renderShellInit(shell, bin string) (string, error) {
	var tmpl string
	switch shell {
	case "zsh":
		tmpl = zshInitTemplate
	case "bash":
		tmpl = bashInitTemplate
	case "powershell", "pwsh":
		tmpl = powershellInitTemplate
	default:
		return "", fmt.Errorf("unsupported shell %q (supported: zsh, bash, powershell)", shell)
	}
	return strings.ReplaceAll(tmpl, "{BIN}", bin), nil
}
